version: '3.9'

services:
  app:
    container_name: property-pulse
    image: property-pulse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - property-pulse
    volumes:
      - .:/app
      - /app/node_modules

networks:
  property-pulse:
    name: property-pulse

volumes:
  property-pulse:
    name: property-pulse
